// This file is auto-generated by @hey-api/openapi-ts

/**
 * Faction Links Response
 * Response containing faction links
 */
export type FactionLinksResponse = {
    data?: FactionLinksData;
};

/**
 * Quest Response
 * Response containing a single quest
 */
export type QuestResponse = {
    data?: Quest;
};

/**
 * Game Parameters
 * Parameters for creating or updating a game
 */
export type GameParams = {
    /**
     * Game description
     */
    description?: string;
    /**
     * Game name
     */
    name: string;
    /**
     * Game setting
     */
    setting?: string;
};

/**
 * Faction Links
 * Collections of entities linked to a faction
 */
export type FactionLinks = {
    /**
     * Linked characters
     */
    characters?: Array<EntityCharacter>;
    /**
     * Linked factions
     */
    factions?: Array<EntityFaction>;
    /**
     * Linked locations
     */
    locations?: Array<EntityLocation>;
    /**
     * Linked notes
     */
    notes?: Array<EntityNote>;
    /**
     * Linked quests
     */
    quests?: Array<EntityQuest>;
};

/**
 * Quest
 * A game quest
 */
export type Quest = {
    /**
     * Quest content
     */
    content: string;
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Associated game ID
     */
    game_id: string;
    /**
     * Quest ID
     */
    id: string;
    /**
     * Quest name
     */
    name: string;
    /**
     * Tags associated with this quest
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
    /**
     * Creator user ID
     */
    user_id: number;
};

/**
 * Error Details
 * Detailed error information
 */
export type ErrorDetails = {
    [key: string]: unknown;
};

/**
 * Login Response
 * Successful login response
 */
export type LoginResponse = {
    /**
     * Session token (Base64 encoded)
     */
    token: string;
    user: User;
};

/**
 * Error
 * Error response
 */
export type _Error = {
    errors?: ErrorDetails;
};

/**
 * Note Links Data
 * Links associated with a note
 */
export type NoteLinksData = {
    links?: NoteLinks;
    /**
     * Note ID
     */
    note_id: string;
    /**
     * Note name
     */
    note_name: string;
};

/**
 * Game Response
 * Response containing a single game
 */
export type GameResponse = {
    data?: Game;
};

/**
 * Entity Note
 * Note entity in game entities list
 */
export type EntityNote = {
    /**
     * Note content
     */
    content: string;
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Note ID
     */
    id: string;
    /**
     * Note name
     */
    name: string;
    /**
     * Tags associated with this note
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
};

/**
 * Entity Location
 * Location entity in game entities list
 */
export type EntityLocation = {
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Location description
     */
    description?: string;
    /**
     * Whether this location has a parent location
     */
    has_parent: boolean;
    /**
     * Location ID
     */
    id: string;
    /**
     * Location name
     */
    name: string;
    /**
     * Tags associated with this location
     */
    tags?: Array<string>;
    /**
     * Location type
     */
    type: 'continent' | 'nation' | 'region' | 'city' | 'settlement' | 'building' | 'complex';
    /**
     * Last update timestamp
     */
    updated_at?: string;
};

/**
 * Game Request
 * Game creation/update parameters
 */
export type GameRequest = {
    game: GameParams;
};

/**
 * Quest Links
 * Collections of entities linked to a quest
 */
export type QuestLinks = {
    /**
     * Linked characters
     */
    characters?: Array<EntityCharacter>;
    /**
     * Linked factions
     */
    factions?: Array<EntityFaction>;
    /**
     * Linked locations
     */
    locations?: Array<EntityLocation>;
    /**
     * Linked notes
     */
    notes?: Array<EntityNote>;
    /**
     * Linked quests
     */
    quests?: Array<EntityQuest>;
};

/**
 * Character Request
 * Character creation/update parameters
 */
export type CharacterRequest = {
    character: CharacterParams;
};

/**
 * Character Response
 * Response containing a single character
 */
export type CharacterResponse = {
    data?: Character;
};

/**
 * Signup Request
 * User registration credentials
 */
export type SignupRequest = {
    /**
     * User email
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

/**
 * Note Links Response
 * Response containing note links
 */
export type NoteLinksResponse = {
    data?: NoteLinksData;
};

/**
 * Note Parameters
 * Parameters for creating or updating a note
 */
export type NoteParams = {
    /**
     * Note content
     */
    content: string;
    /**
     * Note name
     */
    name: string;
    /**
     * Tags for this note
     */
    tags?: Array<string>;
};

/**
 * Location Parameters
 * Parameters for creating or updating a location
 */
export type LocationParams = {
    /**
     * Location description
     */
    description?: string;
    /**
     * Location name
     */
    name: string;
    /**
     * Parent location ID
     */
    parent_id?: string;
    /**
     * Tags for this location
     */
    tags?: Array<string>;
    /**
     * Location type
     */
    type: 'continent' | 'nation' | 'region' | 'city' | 'settlement' | 'building' | 'complex';
};

/**
 * Quests Response
 * Response containing a list of quests
 */
export type QuestsResponse = {
    /**
     * Response data
     */
    data?: Array<Quest>;
};

/**
 * Character Parameters
 * Parameters for creating or updating a character
 */
export type CharacterParams = {
    /**
     * Character class
     */
    class: string;
    /**
     * Character description
     */
    description?: string;
    /**
     * Character image URL
     */
    image_url?: string;
    /**
     * Character level
     */
    level: number;
    /**
     * Character name
     */
    name: string;
    /**
     * Tags for this character
     */
    tags?: Array<string>;
};

/**
 * Quest Links Response
 * Response containing quest links
 */
export type QuestLinksResponse = {
    data?: QuestLinksData;
};

/**
 * Entities Response
 * Response containing all game entities
 */
export type EntitiesResponse = {
    data?: EntitiesData;
};

/**
 * Character
 * A game character
 */
export type Character = {
    /**
     * Character class
     */
    class: string;
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Character description
     */
    description?: string;
    /**
     * Associated game ID
     */
    game_id: string;
    /**
     * Character ID
     */
    id: string;
    /**
     * Character image URL
     */
    image_url?: string;
    /**
     * Character level
     */
    level: number;
    /**
     * Character name
     */
    name: string;
    /**
     * Tags associated with this character
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
    /**
     * Creator user ID
     */
    user_id: number;
};

/**
 * Faction Request
 * Faction creation/update parameters
 */
export type FactionRequest = {
    faction: FactionParams;
};

/**
 * Members Response
 * Response containing a list of game members
 */
export type MembersResponse = {
    /**
     * Response data
     */
    data?: Array<Member>;
};

/**
 * Quest Parameters
 * Parameters for creating or updating a quest
 */
export type QuestParams = {
    /**
     * Quest content
     */
    content: string;
    /**
     * Quest name
     */
    name: string;
    /**
     * Tags for this quest
     */
    tags?: Array<string>;
};

/**
 * Locations Response
 * Response containing a list of locations
 */
export type LocationsResponse = {
    /**
     * Response data
     */
    data?: Array<Location>;
};

/**
 * Entities Data
 * Game entities data structure
 */
export type EntitiesData = {
    entities?: Entities;
    /**
     * Game ID
     */
    game_id: string;
    /**
     * Game name
     */
    game_name: string;
};

/**
 * Note
 * A game note
 */
export type Note = {
    /**
     * Note content
     */
    content: string;
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Associated game ID
     */
    game_id: string;
    /**
     * Note ID
     */
    id: string;
    /**
     * Note name
     */
    name: string;
    /**
     * Tags associated with this note
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
    /**
     * Author user ID
     */
    user_id: number;
};

/**
 * Faction Parameters
 * Parameters for creating or updating a faction
 */
export type FactionParams = {
    /**
     * Faction description
     */
    description: string;
    /**
     * Faction name
     */
    name: string;
    /**
     * Tags for this faction
     */
    tags?: Array<string>;
};

/**
 * Member
 * A game member
 */
export type Member = {
    /**
     * User email
     */
    email: string;
    /**
     * Join timestamp
     */
    joined_at?: string;
    /**
     * Member role
     */
    role: string;
    /**
     * User ID
     */
    user_id: number;
};

/**
 * User
 * User information
 */
export type User = {
    /**
     * Email confirmation timestamp
     */
    confirmed_at?: string;
    /**
     * User email
     */
    email: string;
    /**
     * User ID
     */
    id: number;
};

/**
 * Factions Response
 * Response containing a list of factions
 */
export type FactionsResponse = {
    /**
     * Response data
     */
    data?: Array<Faction>;
};

/**
 * Character Links Response
 * Response containing character links
 */
export type CharacterLinksResponse = {
    data?: CharacterLinksData;
};

/**
 * Characters Response
 * Response containing a list of characters
 */
export type CharactersResponse = {
    /**
     * Response data
     */
    data?: Array<Character>;
};

/**
 * Game
 * A game instance
 */
export type Game = {
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Game description
     */
    description?: string;
    /**
     * Game ID
     */
    id: string;
    /**
     * Game name
     */
    name: string;
    /**
     * Owner user ID
     */
    owner_id: number;
    /**
     * Game setting
     */
    setting?: string;
    /**
     * Last update timestamp
     */
    updated_at?: string;
};

/**
 * Faction
 * A game faction
 */
export type Faction = {
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Faction description
     */
    description: string;
    /**
     * Associated game ID
     */
    game_id: string;
    /**
     * Faction ID
     */
    id: string;
    /**
     * Faction name
     */
    name: string;
    /**
     * Tags associated with this faction
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
    /**
     * Creator user ID
     */
    user_id: number;
};

/**
 * Entities
 * Collection of game entities
 */
export type Entities = {
    /**
     * Characters list
     */
    characters?: Array<EntityCharacter>;
    /**
     * Factions list
     */
    factions?: Array<EntityFaction>;
    /**
     * Locations list
     */
    locations?: Array<EntityLocation>;
    /**
     * Notes list
     */
    notes?: Array<EntityNote>;
    /**
     * Quests list
     */
    quests?: Array<EntityQuest>;
};

/**
 * Location
 * A game location
 */
export type Location = {
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Location description
     */
    description?: string;
    /**
     * Associated game ID
     */
    game_id: string;
    /**
     * Location ID
     */
    id: string;
    /**
     * Location name
     */
    name: string;
    /**
     * Parent location ID
     */
    parent_id?: string;
    /**
     * Tags associated with this location
     */
    tags?: Array<string>;
    /**
     * Location type
     */
    type: 'continent' | 'nation' | 'region' | 'city' | 'settlement' | 'building' | 'complex';
    /**
     * Last update timestamp
     */
    updated_at?: string;
    /**
     * Creator user ID
     */
    user_id: number;
};

/**
 * Note Links
 * Collections of entities linked to a note
 */
export type NoteLinks = {
    /**
     * Linked characters
     */
    characters?: Array<EntityCharacter>;
    /**
     * Linked factions
     */
    factions?: Array<EntityFaction>;
    /**
     * Linked locations
     */
    locations?: Array<EntityLocation>;
    /**
     * Linked notes
     */
    notes?: Array<EntityNote>;
    /**
     * Linked quests
     */
    quests?: Array<EntityQuest>;
};

/**
 * Location Links Data
 * Links associated with a location
 */
export type LocationLinksData = {
    links?: LocationLinks;
    /**
     * Location ID
     */
    location_id: string;
    /**
     * Location name
     */
    location_name: string;
};

/**
 * Link Request
 * Request to create a link between entities
 */
export type LinkRequest = {
    /**
     * Entity ID to link
     */
    entity_id: string;
    /**
     * Entity type to link
     */
    entity_type: 'character' | 'faction' | 'location' | 'quest';
};

/**
 * Location Links Response
 * Response containing location links
 */
export type LocationLinksResponse = {
    data?: LocationLinksData;
};

/**
 * Location Links
 * Collections of entities linked to a location
 */
export type LocationLinks = {
    /**
     * Linked characters
     */
    characters?: Array<EntityCharacter>;
    /**
     * Linked factions
     */
    factions?: Array<EntityFaction>;
    /**
     * Linked locations
     */
    locations?: Array<EntityLocation>;
    /**
     * Linked notes
     */
    notes?: Array<EntityNote>;
    /**
     * Linked quests
     */
    quests?: Array<EntityQuest>;
};

/**
 * Note Request
 * Note creation/update parameters
 */
export type NoteRequest = {
    note: NoteParams;
};

/**
 * Location Request
 * Location creation/update parameters
 */
export type LocationRequest = {
    location: LocationParams;
};

/**
 * Faction Response
 * Response containing a single faction
 */
export type FactionResponse = {
    data?: Faction;
};

/**
 * Login Request
 * Login credentials - either email/password or magic link token
 */
export type LoginRequest = {
    /**
     * User email
     */
    email?: string;
    /**
     * User password
     */
    password?: string;
    /**
     * Magic link token
     */
    token?: string;
};

/**
 * Faction Links Data
 * Links associated with a faction
 */
export type FactionLinksData = {
    /**
     * Faction ID
     */
    faction_id: string;
    /**
     * Faction name
     */
    faction_name: string;
    links?: FactionLinks;
};

/**
 * Entity Character
 * Character entity in game entities list
 */
export type EntityCharacter = {
    /**
     * Character class
     */
    class: string;
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Character description
     */
    description?: string;
    /**
     * Character ID
     */
    id: string;
    /**
     * Character image URL
     */
    image_url?: string;
    /**
     * Character level
     */
    level: number;
    /**
     * Character name
     */
    name: string;
    /**
     * Tags associated with this character
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
};

/**
 * Location Response
 * Response containing a single location
 */
export type LocationResponse = {
    data?: Location;
};

/**
 * Notes Response
 * Response containing a list of notes
 */
export type NotesResponse = {
    /**
     * Response data
     */
    data?: Array<Note>;
};

/**
 * Games Response
 * Response containing a list of games
 */
export type GamesResponse = {
    /**
     * Response data
     */
    data?: Array<Game>;
};

/**
 * Auth Status Response
 * Authentication status response
 */
export type AuthStatusResponse = {
    /**
     * Whether user is authenticated
     */
    authenticated: boolean;
    user?: User;
};

/**
 * Character Links
 * Collections of entities linked to a character
 */
export type CharacterLinks = {
    /**
     * Linked characters
     */
    characters?: Array<EntityCharacter>;
    /**
     * Linked factions
     */
    factions?: Array<EntityFaction>;
    /**
     * Linked locations
     */
    locations?: Array<EntityLocation>;
    /**
     * Linked notes
     */
    notes?: Array<EntityNote>;
    /**
     * Linked quests
     */
    quests?: Array<EntityQuest>;
};

/**
 * Entity Faction
 * Faction entity in game entities list
 */
export type EntityFaction = {
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Faction description
     */
    description: string;
    /**
     * Faction ID
     */
    id: string;
    /**
     * Faction name
     */
    name: string;
    /**
     * Tags associated with this faction
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
};

/**
 * Note Response
 * Response containing a single note
 */
export type NoteResponse = {
    data?: Note;
};

/**
 * Quest Links Data
 * Links associated with a quest
 */
export type QuestLinksData = {
    links?: QuestLinks;
    /**
     * Quest ID
     */
    quest_id: string;
    /**
     * Quest name
     */
    quest_name: string;
};

/**
 * Entity Quest
 * Quest entity in game entities list
 */
export type EntityQuest = {
    /**
     * Quest content
     */
    content: string;
    /**
     * Creation timestamp
     */
    created_at?: string;
    /**
     * Quest ID
     */
    id: string;
    /**
     * Quest name
     */
    name: string;
    /**
     * Tags associated with this quest
     */
    tags?: Array<string>;
    /**
     * Last update timestamp
     */
    updated_at?: string;
};

/**
 * Character Links Data
 * Links associated with a character
 */
export type CharacterLinksData = {
    /**
     * Character ID
     */
    character_id: string;
    /**
     * Character name
     */
    character_name: string;
    links?: CharacterLinks;
};

/**
 * Quest Request
 * Quest creation/update parameters
 */
export type QuestRequest = {
    quest: QuestParams;
};

export type LoginUserData = {
    /**
     * Login credentials
     */
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginUserErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Success
     */
    200: LoginResponse;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutUserErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
};

export type LogoutUserError = LogoutUserErrors[keyof LogoutUserErrors];

export type LogoutUserResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type SignupUserData = {
    /**
     * Signup credentials
     */
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupUserErrors = {
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type SignupUserError = SignupUserErrors[keyof SignupUserErrors];

export type SignupUserResponses = {
    /**
     * Created
     */
    201: LoginResponse;
};

export type SignupUserResponse = SignupUserResponses[keyof SignupUserResponses];

export type GetAuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/status';
};

export type GetAuthStatusErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
};

export type GetAuthStatusError = GetAuthStatusErrors[keyof GetAuthStatusErrors];

export type GetAuthStatusResponses = {
    /**
     * Success
     */
    200: AuthStatusResponse;
};

export type GetAuthStatusResponse = GetAuthStatusResponses[keyof GetAuthStatusResponses];

export type ListGamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games';
};

export type ListGamesErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
};

export type ListGamesError = ListGamesErrors[keyof ListGamesErrors];

export type ListGamesResponses = {
    /**
     * Success
     */
    200: GamesResponse;
};

export type ListGamesResponse = ListGamesResponses[keyof ListGamesResponses];

export type CreateGameData = {
    /**
     * Game parameters
     */
    body: GameRequest;
    path?: never;
    query?: never;
    url: '/api/games';
};

export type CreateGameErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateGameError = CreateGameErrors[keyof CreateGameErrors];

export type CreateGameResponses = {
    /**
     * Created
     */
    201: GameResponse;
};

export type CreateGameResponse = CreateGameResponses[keyof CreateGameResponses];

export type ListCharactersData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters';
};

export type ListCharactersErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListCharactersError = ListCharactersErrors[keyof ListCharactersErrors];

export type ListCharactersResponses = {
    /**
     * Success
     */
    200: CharactersResponse;
};

export type ListCharactersResponse = ListCharactersResponses[keyof ListCharactersResponses];

export type CreateCharacterData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters';
};

export type CreateCharacterErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateCharacterError = CreateCharacterErrors[keyof CreateCharacterErrors];

export type CreateCharacterResponses = {
    /**
     * Created
     */
    201: CharacterResponse;
};

export type CreateCharacterResponse = CreateCharacterResponses[keyof CreateCharacterResponses];

export type GetCharacterLinksData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Character ID
         */
        character_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters/{character_id}/links';
};

export type GetCharacterLinksErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetCharacterLinksError = GetCharacterLinksErrors[keyof GetCharacterLinksErrors];

export type GetCharacterLinksResponses = {
    /**
     * Success
     */
    200: CharacterLinksResponse;
};

export type GetCharacterLinksResponse = GetCharacterLinksResponses[keyof GetCharacterLinksResponses];

export type CreateCharacterLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Character ID
         */
        character_id: string;
    };
    query: {
        /**
         * Entity type to link
         */
        entity_type: 'faction' | 'location' | 'quest' | 'note' | 'character';
        /**
         * Entity ID to link
         */
        entity_id: string;
    };
    url: '/api/games/{game_id}/characters/{character_id}/links';
};

export type CreateCharacterLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateCharacterLinkError = CreateCharacterLinkErrors[keyof CreateCharacterLinkErrors];

export type CreateCharacterLinkResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteCharacterLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Character ID
         */
        character_id: string;
        /**
         * Entity type
         */
        entity_type: string;
        /**
         * Entity ID
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters/{character_id}/links/{entity_type}/{entity_id}';
};

export type DeleteCharacterLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteCharacterLinkError = DeleteCharacterLinkErrors[keyof DeleteCharacterLinkErrors];

export type DeleteCharacterLinkResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteCharacterData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Character ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters/{id}';
};

export type DeleteCharacterErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteCharacterError = DeleteCharacterErrors[keyof DeleteCharacterErrors];

export type DeleteCharacterResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetCharacterData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Character ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters/{id}';
};

export type GetCharacterErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetCharacterError = GetCharacterErrors[keyof GetCharacterErrors];

export type GetCharacterResponses = {
    /**
     * Success
     */
    200: CharacterResponse;
};

export type GetCharacterResponse = GetCharacterResponses[keyof GetCharacterResponses];

export type UpdateCharacterData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Character ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/characters/{id}';
};

export type UpdateCharacterErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type UpdateCharacterError = UpdateCharacterErrors[keyof UpdateCharacterErrors];

export type UpdateCharacterResponses = {
    /**
     * Success
     */
    200: CharacterResponse;
};

export type UpdateCharacterResponse = UpdateCharacterResponses[keyof UpdateCharacterResponses];

export type ListFactionsData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions';
};

export type ListFactionsErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListFactionsError = ListFactionsErrors[keyof ListFactionsErrors];

export type ListFactionsResponses = {
    /**
     * Success
     */
    200: FactionsResponse;
};

export type ListFactionsResponse = ListFactionsResponses[keyof ListFactionsResponses];

export type CreateFactionData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions';
};

export type CreateFactionErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateFactionError = CreateFactionErrors[keyof CreateFactionErrors];

export type CreateFactionResponses = {
    /**
     * Created
     */
    201: FactionResponse;
};

export type CreateFactionResponse = CreateFactionResponses[keyof CreateFactionResponses];

export type GetFactionLinksData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Faction ID
         */
        faction_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions/{faction_id}/links';
};

export type GetFactionLinksErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetFactionLinksError = GetFactionLinksErrors[keyof GetFactionLinksErrors];

export type GetFactionLinksResponses = {
    /**
     * Success
     */
    200: FactionLinksResponse;
};

export type GetFactionLinksResponse = GetFactionLinksResponses[keyof GetFactionLinksResponses];

export type CreateFactionLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Faction ID
         */
        faction_id: string;
    };
    query: {
        /**
         * Entity type to link
         */
        entity_type: 'character' | 'location' | 'quest' | 'note' | 'faction';
        /**
         * Entity ID to link
         */
        entity_id: string;
    };
    url: '/api/games/{game_id}/factions/{faction_id}/links';
};

export type CreateFactionLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateFactionLinkError = CreateFactionLinkErrors[keyof CreateFactionLinkErrors];

export type CreateFactionLinkResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteFactionLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Faction ID
         */
        faction_id: string;
        /**
         * Entity type
         */
        entity_type: 'character' | 'location' | 'quest' | 'note' | 'faction';
        /**
         * Entity ID
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions/{faction_id}/links/{entity_type}/{entity_id}';
};

export type DeleteFactionLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteFactionLinkError = DeleteFactionLinkErrors[keyof DeleteFactionLinkErrors];

export type DeleteFactionLinkResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteFactionData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Faction ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions/{id}';
};

export type DeleteFactionErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteFactionError = DeleteFactionErrors[keyof DeleteFactionErrors];

export type DeleteFactionResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetFactionData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Faction ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions/{id}';
};

export type GetFactionErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetFactionError = GetFactionErrors[keyof GetFactionErrors];

export type GetFactionResponses = {
    /**
     * Success
     */
    200: FactionResponse;
};

export type GetFactionResponse = GetFactionResponses[keyof GetFactionResponses];

export type UpdateFactionData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Faction ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/factions/{id}';
};

export type UpdateFactionErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type UpdateFactionError = UpdateFactionErrors[keyof UpdateFactionErrors];

export type UpdateFactionResponses = {
    /**
     * Success
     */
    200: FactionResponse;
};

export type UpdateFactionResponse = UpdateFactionResponses[keyof UpdateFactionResponses];

export type ListGameEntitiesData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/links';
};

export type ListGameEntitiesErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListGameEntitiesError = ListGameEntitiesErrors[keyof ListGameEntitiesErrors];

export type ListGameEntitiesResponses = {
    /**
     * Success
     */
    200: EntitiesResponse;
};

export type ListGameEntitiesResponse = ListGameEntitiesResponses[keyof ListGameEntitiesResponses];

export type ListLocationsData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations';
};

export type ListLocationsErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListLocationsError = ListLocationsErrors[keyof ListLocationsErrors];

export type ListLocationsResponses = {
    /**
     * Success
     */
    200: LocationsResponse;
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type CreateLocationData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations';
};

export type CreateLocationErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * Created
     */
    201: LocationResponse;
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type DeleteLocationData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Location ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations/{id}';
};

export type DeleteLocationErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteLocationError = DeleteLocationErrors[keyof DeleteLocationErrors];

export type DeleteLocationResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetLocationData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Location ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations/{id}';
};

export type GetLocationErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetLocationError = GetLocationErrors[keyof GetLocationErrors];

export type GetLocationResponses = {
    /**
     * Success
     */
    200: LocationResponse;
};

export type GetLocationResponse = GetLocationResponses[keyof GetLocationResponses];

export type UpdateLocationData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Location ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations/{id}';
};

export type UpdateLocationErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type UpdateLocationError = UpdateLocationErrors[keyof UpdateLocationErrors];

export type UpdateLocationResponses = {
    /**
     * Success
     */
    200: LocationResponse;
};

export type UpdateLocationResponse = UpdateLocationResponses[keyof UpdateLocationResponses];

export type GetLocationLinksData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Location ID
         */
        location_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations/{location_id}/links';
};

export type GetLocationLinksErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetLocationLinksError = GetLocationLinksErrors[keyof GetLocationLinksErrors];

export type GetLocationLinksResponses = {
    /**
     * Success
     */
    200: LocationLinksResponse;
};

export type GetLocationLinksResponse = GetLocationLinksResponses[keyof GetLocationLinksResponses];

export type CreateLocationLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Location ID
         */
        location_id: string;
    };
    query: {
        /**
         * Entity type to link
         */
        entity_type: 'character' | 'faction' | 'location' | 'quest' | 'note';
        /**
         * Entity ID to link
         */
        entity_id: string;
    };
    url: '/api/games/{game_id}/locations/{location_id}/links';
};

export type CreateLocationLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateLocationLinkError = CreateLocationLinkErrors[keyof CreateLocationLinkErrors];

export type CreateLocationLinkResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteLocationLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Location ID
         */
        location_id: string;
        /**
         * Entity type
         */
        entity_type: 'character' | 'faction' | 'location' | 'quest' | 'note';
        /**
         * Entity ID
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/locations/{location_id}/links/{entity_type}/{entity_id}';
};

export type DeleteLocationLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteLocationLinkError = DeleteLocationLinkErrors[keyof DeleteLocationLinkErrors];

export type DeleteLocationLinkResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListGameMembersData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/members';
};

export type ListGameMembersErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListGameMembersError = ListGameMembersErrors[keyof ListGameMembersErrors];

export type ListGameMembersResponses = {
    /**
     * Success
     */
    200: MembersResponse;
};

export type ListGameMembersResponse = ListGameMembersResponses[keyof ListGameMembersResponses];

export type AddGameMemberData = {
    body: {
        /**
         * User ID to add
         */
        user_id: number;
        /**
         * Member role (default: 'member')
         */
        role?: string;
    };
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/members';
};

export type AddGameMemberErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type AddGameMemberError = AddGameMemberErrors[keyof AddGameMemberErrors];

export type AddGameMemberResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type RemoveGameMemberData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * User ID to remove
         */
        user_id: number;
    };
    query?: never;
    url: '/api/games/{game_id}/members/{user_id}';
};

export type RemoveGameMemberErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type RemoveGameMemberError = RemoveGameMemberErrors[keyof RemoveGameMemberErrors];

export type RemoveGameMemberResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListNotesData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes';
};

export type ListNotesErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListNotesError = ListNotesErrors[keyof ListNotesErrors];

export type ListNotesResponses = {
    /**
     * Success
     */
    200: NotesResponse;
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type CreateNoteData = {
    /**
     * Note parameters
     */
    body: NoteRequest;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes';
};

export type CreateNoteErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateNoteError = CreateNoteErrors[keyof CreateNoteErrors];

export type CreateNoteResponses = {
    /**
     * Created
     */
    201: NoteResponse;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type DeleteNoteData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Note ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes/{id}';
};

export type DeleteNoteErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteNoteError = DeleteNoteErrors[keyof DeleteNoteErrors];

export type DeleteNoteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetNoteData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Note ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes/{id}';
};

export type GetNoteErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetNoteError = GetNoteErrors[keyof GetNoteErrors];

export type GetNoteResponses = {
    /**
     * Success
     */
    200: NoteResponse;
};

export type GetNoteResponse = GetNoteResponses[keyof GetNoteResponses];

export type UpdateNoteData = {
    /**
     * Note parameters
     */
    body: NoteRequest;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Note ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes/{id}';
};

export type UpdateNoteErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type UpdateNoteError = UpdateNoteErrors[keyof UpdateNoteErrors];

export type UpdateNoteResponses = {
    /**
     * Success
     */
    200: NoteResponse;
};

export type UpdateNoteResponse = UpdateNoteResponses[keyof UpdateNoteResponses];

export type GetNoteLinksData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Note ID
         */
        note_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes/{note_id}/links';
};

export type GetNoteLinksErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetNoteLinksError = GetNoteLinksErrors[keyof GetNoteLinksErrors];

export type GetNoteLinksResponses = {
    /**
     * Success
     */
    200: NoteLinksResponse;
};

export type GetNoteLinksResponse = GetNoteLinksResponses[keyof GetNoteLinksResponses];

export type CreateNoteLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Note ID
         */
        note_id: string;
    };
    query: {
        /**
         * Entity type to link
         */
        entity_type: 'character' | 'faction' | 'location' | 'quest' | 'note';
        /**
         * Entity ID to link
         */
        entity_id: string;
    };
    url: '/api/games/{game_id}/notes/{note_id}/links';
};

export type CreateNoteLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateNoteLinkError = CreateNoteLinkErrors[keyof CreateNoteLinkErrors];

export type CreateNoteLinkResponses = {
    /**
     * Created
     */
    201: {
        entity_id?: string;
        entity_type?: string;
        message?: string;
        note_id?: string;
    };
};

export type CreateNoteLinkResponse = CreateNoteLinkResponses[keyof CreateNoteLinkResponses];

export type DeleteNoteLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Note ID
         */
        note_id: string;
        /**
         * Entity type
         */
        entity_type: 'character' | 'faction' | 'location' | 'quest' | 'note';
        /**
         * Entity ID
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/notes/{note_id}/links/{entity_type}/{entity_id}';
};

export type DeleteNoteLinkErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type DeleteNoteLinkError = DeleteNoteLinkErrors[keyof DeleteNoteLinkErrors];

export type DeleteNoteLinkResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListQuestsData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests';
};

export type ListQuestsErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type ListQuestsError = ListQuestsErrors[keyof ListQuestsErrors];

export type ListQuestsResponses = {
    /**
     * Success
     */
    200: QuestsResponse;
};

export type ListQuestsResponse = ListQuestsResponses[keyof ListQuestsResponses];

export type CreateQuestData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests';
};

export type CreateQuestErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateQuestError = CreateQuestErrors[keyof CreateQuestErrors];

export type CreateQuestResponses = {
    /**
     * Created
     */
    201: QuestResponse;
};

export type CreateQuestResponse = CreateQuestResponses[keyof CreateQuestResponses];

export type DeleteQuestData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Quest ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests/{id}';
};

export type DeleteQuestErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteQuestError = DeleteQuestErrors[keyof DeleteQuestErrors];

export type DeleteQuestResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetQuestData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Quest ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests/{id}';
};

export type GetQuestErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetQuestError = GetQuestErrors[keyof GetQuestErrors];

export type GetQuestResponses = {
    /**
     * Success
     */
    200: QuestResponse;
};

export type GetQuestResponse = GetQuestResponses[keyof GetQuestResponses];

export type UpdateQuestData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Quest ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests/{id}';
};

export type UpdateQuestErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type UpdateQuestError = UpdateQuestErrors[keyof UpdateQuestErrors];

export type UpdateQuestResponses = {
    /**
     * Success
     */
    200: QuestResponse;
};

export type UpdateQuestResponse = UpdateQuestResponses[keyof UpdateQuestResponses];

export type GetQuestLinksData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Quest ID
         */
        quest_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests/{quest_id}/links';
};

export type GetQuestLinksErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetQuestLinksError = GetQuestLinksErrors[keyof GetQuestLinksErrors];

export type GetQuestLinksResponses = {
    /**
     * Success
     */
    200: QuestLinksResponse;
};

export type GetQuestLinksResponse = GetQuestLinksResponses[keyof GetQuestLinksResponses];

export type CreateQuestLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Quest ID
         */
        quest_id: string;
    };
    query: {
        /**
         * Entity type to link
         */
        entity_type: 'character' | 'faction' | 'location' | 'note' | 'quest';
        /**
         * Entity ID to link
         */
        entity_id: string;
    };
    url: '/api/games/{game_id}/quests/{quest_id}/links';
};

export type CreateQuestLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type CreateQuestLinkError = CreateQuestLinkErrors[keyof CreateQuestLinkErrors];

export type CreateQuestLinkResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteQuestLinkData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        game_id: string;
        /**
         * Quest ID
         */
        quest_id: string;
        /**
         * Entity type
         */
        entity_type: 'character' | 'faction' | 'location' | 'note' | 'quest';
        /**
         * Entity ID
         */
        entity_id: string;
    };
    query?: never;
    url: '/api/games/{game_id}/quests/{quest_id}/links/{entity_type}/{entity_id}';
};

export type DeleteQuestLinkErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden
     */
    403: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteQuestLinkError = DeleteQuestLinkErrors[keyof DeleteQuestLinkErrors];

export type DeleteQuestLinkResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteGameData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}';
};

export type DeleteGameErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type DeleteGameError = DeleteGameErrors[keyof DeleteGameErrors];

export type DeleteGameResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetGameData = {
    body?: never;
    path: {
        /**
         * Game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}';
};

export type GetGameErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
};

export type GetGameError = GetGameErrors[keyof GetGameErrors];

export type GetGameResponses = {
    /**
     * Success
     */
    200: GameResponse;
};

export type GetGameResponse = GetGameResponses[keyof GetGameResponses];

export type UpdateGameData = {
    /**
     * Game parameters
     */
    body: GameRequest;
    path: {
        /**
         * Game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}';
};

export type UpdateGameErrors = {
    /**
     * Bad Request
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Not Found
     */
    404: _Error;
    /**
     * Unprocessable Entity
     */
    422: _Error;
};

export type UpdateGameError = UpdateGameErrors[keyof UpdateGameErrors];

export type UpdateGameResponses = {
    /**
     * Success
     */
    200: GameResponse;
};

export type UpdateGameResponse = UpdateGameResponses[keyof UpdateGameResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};