// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Linked Character
 * A character with relationship metadata
 */
export const zLinkedCharacterWithCurrentLocation = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    is_current_location: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Quest Tree Node
 * A node in the quest hierarchy tree
 */
export const zQuestTreeNode = z.object({
    get children(): z.ZodOptional {
        return z.optional(z.array(z.lazy((): any => {
            return zQuestTreeNode;
        })));
    },
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    entity_type: z.enum([
        'quest'
    ]),
    id: z.uuid(),
    name: z.string(),
    parent_id: z.optional(z.uuid()),
    status: z.enum([
        'preparing',
        'ready',
        'active',
        'paused',
        'completed',
        'cancelled'
    ]),
    tags: z.optional(z.array(z.string()))
});

/**
 * Character Create Parameters
 * Parameters for creating a new character
 */
export const zCharacterCreateParams = z.object({
    alive: z.optional(z.boolean()),
    class: z.string(),
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    level: z.int(),
    name: z.string(),
    race: z.optional(z.string()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Character Creation Link
 * Link definition for character creation
 */
export const zCharacterCreationLink = z.object({
    description: z.optional(z.string()),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    faction_role: z.optional(z.string()),
    is_active: z.optional(z.boolean()).default(true),
    is_current_location: z.optional(z.boolean()).default(false),
    is_primary: z.optional(z.boolean()).default(false),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

/**
 * Character Create Request
 * Character creation parameters with optional entity links
 */
export const zCharacterCreateRequest = z.object({
    character: zCharacterCreateParams,
    links: z.optional(z.array(zCharacterCreationLink))
});

/**
 * Note Update Parameters
 * Parameters for updating an existing note (partial updates supported)
 */
export const zNoteUpdateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.optional(z.string()),
    pinned: z.optional(z.boolean()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Image
 * An image associated with a game entity
 */
export const zImage = z.object({
    alt_text: z.optional(z.string()),
    content_type: z.enum([
        'image/jpeg',
        'image/jpg',
        'image/png',
        'image/webp',
        'image/gif'
    ]),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    file_size: z.int().gte(1),
    file_size_mb: z.number(),
    file_url: z.string(),
    filename: z.string(),
    id: z.uuid(),
    inserted_at: z.iso.datetime(),
    is_primary: z.boolean(),
    metadata: z.optional(z.record(z.string(), z.unknown())).default({}),
    position_y: z.int().gte(0).lte(100).default(50),
    updated_at: z.iso.datetime()
});

/**
 * Faction Update Parameters
 * Parameters for updating an existing faction (partial updates supported)
 */
export const zFactionUpdateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.optional(z.string()),
    pinned: z.optional(z.boolean()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Quest Creation Link
 * Link definition for quest creation
 */
export const zQuestCreationLink = z.object({
    description: z.optional(z.string()),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    is_active: z.optional(z.boolean()).default(true),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    objective_type: z.optional(z.string()),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

/**
 * Location Create Parameters
 * Parameters for creating a new location
 */
export const zLocationCreateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.string(),
    parent_id: z.optional(z.uuid()),
    tags: z.optional(z.array(z.string())),
    type: z.enum([
        'continent',
        'nation',
        'region',
        'city',
        'settlement',
        'building',
        'complex'
    ])
});

/**
 * Location Create Request
 * Location creation parameters
 */
export const zLocationCreateRequest = z.object({
    location: zLocationCreateParams
});

/**
 * Note Create Parameters
 * Parameters for creating a new note
 */
export const zNoteCreateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.string(),
    tags: z.optional(z.array(z.string()))
});

/**
 * Note Create Request
 * Note creation parameters
 */
export const zNoteCreateRequest = z.object({
    note: zNoteCreateParams
});

/**
 * Objective
 * A quest objective
 */
export const zObjective = z.object({
    body: z.string(),
    complete: z.boolean(),
    id: z.uuid(),
    inserted_at: z.iso.datetime(),
    note_link_id: z.optional(z.uuid()),
    quest_id: z.uuid(),
    updated_at: z.iso.datetime()
});

/**
 * User
 * User information
 */
export const zUser = z.object({
    avatar_url: z.optional(z.string()),
    confirmed_at: z.optional(z.string()),
    email: z.string(),
    id: z.uuid(),
    username: z.optional(z.string())
});

/**
 * Success Response
 * Generic success response
 */
export const zSuccessResponse = z.object({
    message: z.string(),
    profile: z.optional(zUser)
});

/**
 * Linked Character
 * A character with relationship metadata
 */
export const zLinkedCharacter = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Linked Faction
 * A faction with relationship metadata
 */
export const zLinkedFaction = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Linked Location
 * A location with relationship metadata
 */
export const zLinkedLocation = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Linked Note
 * A note with relationship metadata
 */
export const zLinkedNote = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Linked Quest
 * A quest with relationship metadata
 */
export const zLinkedQuest = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Quest Links
 * Collections of entities linked to a quest
 */
export const zQuestLinks = z.object({
    characters: z.optional(z.array(zLinkedCharacter)),
    factions: z.optional(z.array(zLinkedFaction)),
    locations: z.optional(z.array(zLinkedLocation)),
    notes: z.optional(z.array(zLinkedNote)),
    quests: z.optional(z.array(zLinkedQuest))
});

/**
 * Quest Links Data
 * Links associated with a quest
 */
export const zQuestLinksData = z.object({
    links: z.optional(zQuestLinks),
    quest_id: z.uuid(),
    quest_name: z.string()
});

/**
 * Quest Links Response
 * Response containing quest links
 */
export const zQuestLinksResponse = z.object({
    data: z.optional(zQuestLinksData)
});

/**
 * Note Update Request
 * Note update parameters
 */
export const zNoteUpdateRequest = z.object({
    note: zNoteUpdateParams
});

/**
 * Quest Update Parameters
 * Parameters for updating an existing quest (partial updates supported)
 */
export const zQuestUpdateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.optional(z.string()),
    parent_id: z.optional(z.uuid()),
    pinned: z.optional(z.boolean()),
    status: z.optional(z.enum([
        'preparing',
        'ready',
        'active',
        'paused',
        'completed',
        'cancelled'
    ])),
    tags: z.optional(z.array(z.string()))
});

/**
 * Location Tree Node
 * A node in the location hierarchy tree
 */
export const zLocationTreeNode = z.object({
    get children(): z.ZodOptional {
        return z.optional(z.array(z.lazy((): any => {
            return zLocationTreeNode;
        })));
    },
    content: z.optional(z.string()),
    entity_type: z.enum([
        'location'
    ]),
    id: z.uuid(),
    name: z.string(),
    parent_id: z.optional(z.uuid()),
    tags: z.optional(z.array(z.string())),
    type: z.enum([
        'continent',
        'nation',
        'region',
        'city',
        'settlement',
        'building',
        'complex'
    ])
});

/**
 * Location Tree Response
 * Response containing hierarchical location tree
 */
export const zLocationTreeResponse = z.object({
    data: z.optional(z.array(zLocationTreeNode))
});

/**
 * Note Links
 * Collections of entities linked to a note
 */
export const zNoteLinks = z.object({
    characters: z.optional(z.array(zLinkedCharacter)),
    factions: z.optional(z.array(zLinkedFaction)),
    locations: z.optional(z.array(zLinkedLocation)),
    notes: z.optional(z.array(zLinkedNote)),
    quests: z.optional(z.array(zLinkedQuest))
});

/**
 * Note Links Data
 * Links associated with a note
 */
export const zNoteLinksData = z.object({
    links: z.optional(zNoteLinks),
    note_id: z.uuid(),
    note_name: z.string()
});

/**
 * Quest Update Request
 * Quest update parameters
 */
export const zQuestUpdateRequest = z.object({
    quest: zQuestUpdateParams
});

/**
 * Link Request
 * Request to create a link between entities
 */
export const zLinkRequest = z.object({
    description: z.optional(z.string()),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    faction_role: z.optional(z.string()),
    is_active: z.optional(z.boolean()).default(true),
    is_current_location: z.optional(z.boolean()),
    is_primary: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

/**
 * Error Details
 * Detailed error information
 */
export const zErrorDetails = z.record(z.string(), z.unknown());

/**
 * Error
 * Error response
 */
export const zError = z.object({
    errors: z.optional(zErrorDetails)
});

/**
 * Faction
 * A game faction
 */
export const zFaction = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    created_at: z.optional(z.string()),
    game_id: z.uuid(),
    id: z.uuid(),
    name: z.string(),
    pinned: z.boolean(),
    tags: z.optional(z.array(z.string())),
    updated_at: z.optional(z.string()),
    user_id: z.uuid()
});

/**
 * Factions Response
 * Response containing a list of factions
 */
export const zFactionsResponse = z.object({
    data: z.optional(z.array(zFaction))
});

/**
 * Linked Faction
 * A faction with relationship metadata
 */
export const zLinkedFactionWithPrimary = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    faction_role: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    is_primary: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Linked Location
 * A location with relationship metadata
 */
export const zLinkedLocationWithCurrent = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    is_current_location: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Character Links
 * Collections of entities linked to a character
 */
export const zCharacterLinks = z.object({
    characters: z.optional(z.array(zLinkedCharacter)),
    factions: z.optional(z.array(zLinkedFactionWithPrimary)),
    locations: z.optional(z.array(zLinkedLocationWithCurrent)),
    notes: z.optional(z.array(zLinkedNote)),
    quests: z.optional(z.array(zLinkedQuest))
});

/**
 * Character Links Data
 * Links associated with a character
 */
export const zCharacterLinksData = z.object({
    character_id: z.uuid(),
    character_name: z.string(),
    links: z.optional(zCharacterLinks)
});

/**
 * Character
 * A game character
 */
export const zCharacter = z.object({
    alive: z.boolean(),
    class: z.string(),
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    created_at: z.optional(z.string()),
    game_id: z.uuid(),
    id: z.uuid(),
    level: z.int(),
    name: z.string(),
    pinned: z.boolean(),
    race: z.optional(z.string()),
    tags: z.optional(z.array(z.string())),
    updated_at: z.optional(z.string()),
    user_id: z.uuid()
});

/**
 * Location
 * A game location
 */
export const zLocation = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    created_at: z.optional(z.string()),
    game_id: z.uuid(),
    id: z.uuid(),
    name: z.string(),
    parent_id: z.optional(z.uuid()),
    pinned: z.boolean(),
    tags: z.optional(z.array(z.string())),
    type: z.enum([
        'continent',
        'nation',
        'region',
        'city',
        'settlement',
        'building',
        'complex'
    ]),
    updated_at: z.optional(z.string())
});

/**
 * Note
 * A game note
 */
export const zNote = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    created_at: z.optional(z.string()),
    game_id: z.uuid(),
    id: z.uuid(),
    name: z.string(),
    pinned: z.boolean(),
    tags: z.optional(z.array(z.string())),
    updated_at: z.optional(z.string()),
    user_id: z.uuid()
});

/**
 * Quest
 * A game quest
 */
export const zQuest = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    created_at: z.optional(z.string()),
    game_id: z.uuid(),
    id: z.uuid(),
    name: z.string(),
    parent_id: z.optional(z.uuid()),
    pinned: z.boolean(),
    status: z.enum([
        'preparing',
        'ready',
        'active',
        'paused',
        'completed',
        'cancelled'
    ]),
    tags: z.optional(z.array(z.string())),
    updated_at: z.optional(z.string()),
    user_id: z.uuid()
});

/**
 * Entities
 * Collection of game entities
 */
export const zEntities = z.object({
    characters: z.optional(z.array(zCharacter)),
    factions: z.optional(z.array(zFaction)),
    locations: z.optional(z.array(zLocation)),
    notes: z.optional(z.array(zNote)),
    quests: z.optional(z.array(zQuest))
});

/**
 * Note Links Response
 * Response containing note links
 */
export const zNoteLinksResponse = z.object({
    data: z.optional(zNoteLinksData)
});

/**
 * Note Response
 * Response containing a single note
 */
export const zNoteResponse = z.object({
    data: z.optional(zNote)
});

/**
 * Email Change Confirm
 * Confirm email address change with token
 */
export const zEmailChangeConfirm = z.object({
    token: z.string()
});

/**
 * Location Response
 * Response containing a single location
 */
export const zLocationResponse = z.object({
    data: z.optional(zLocation)
});

/**
 * Image Response
 * Response containing a single image
 */
export const zImageResponse = z.object({
    data: z.optional(zImage)
});

/**
 * Entity Tree Node
 * A single node in the entity relationship tree
 */
export const zEntityTreeNode = z.object({
    get children() {
        return z.array(z.lazy((): any => {
            return zEntityTreeNode;
        }));
    },
    description: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(5)),
    type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ])
});

/**
 * Entity Tree Data
 * Entity relationship tree data grouped by entity types or single tree
 */
export const zEntityTreeData = z.object({
    characters: z.optional(z.array(zEntityTreeNode)),
    factions: z.optional(z.array(zEntityTreeNode)),
    locations: z.optional(z.array(zEntityTreeNode)),
    notes: z.optional(z.array(zEntityTreeNode)),
    quests: z.optional(z.array(zEntityTreeNode))
});

/**
 * Entity Tree Response
 * Response containing hierarchical tree of entity relationships
 */
export const zEntityTreeResponse = z.object({
    data: z.optional(zEntityTreeData)
});

/**
 * Faction Creation Link
 * Link definition for faction creation
 */
export const zFactionCreationLink = z.object({
    description: z.optional(z.string()),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    is_active: z.optional(z.boolean()).default(true),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

export const zLinkedEntityBase = z.object({
    description: z.optional(z.string()),
    is_active: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int())
});

/**
 * Faction Update Request
 * Faction update parameters
 */
export const zFactionUpdateRequest = z.object({
    faction: zFactionUpdateParams
});

/**
 * Character Primary Faction Data
 * Primary faction information for a character
 */
export const zCharacterPrimaryFactionData = z.object({
    character_id: z.uuid(),
    faction: zFaction,
    role: z.string()
});

/**
 * Link Update Request
 * Request to update link metadata between entities
 */
export const zLinkUpdateRequest = z.object({
    description: z.optional(z.string()),
    faction_role: z.optional(z.string()),
    is_active: z.optional(z.boolean()),
    is_current_location: z.optional(z.boolean()),
    is_primary: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

/**
 * Login Response
 * Successful login response
 */
export const zLoginResponse = z.object({
    token: z.string(),
    user: zUser
});

/**
 * Character Primary Faction Response
 * Response containing character's primary faction data
 */
export const zCharacterPrimaryFactionResponse = z.object({
    data: z.optional(zCharacterPrimaryFactionData)
});

/**
 * Login Request
 * Login credentials - either email/password or magic link token
 */
export const zLoginRequest = z.object({
    email: z.optional(z.string()),
    password: z.optional(z.string()),
    token: z.optional(z.string())
});

/**
 * Character Update Parameters
 * Parameters for updating an existing character (partial updates supported)
 */
export const zCharacterUpdateParams = z.object({
    alive: z.optional(z.boolean()),
    class: z.optional(z.string()),
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    level: z.optional(z.int()),
    name: z.optional(z.string()),
    pinned: z.optional(z.boolean()),
    race: z.optional(z.string()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Game Update Parameters
 * Parameters for updating an existing game (partial updates supported)
 */
export const zGameUpdateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.optional(z.string()),
    setting: z.optional(z.string())
});

/**
 * Pinned Entities
 * Collection of pinned entities grouped by type
 */
export const zPinnedEntities = z.object({
    characters: z.optional(z.array(zCharacter)),
    factions: z.optional(z.array(zFaction)),
    locations: z.optional(z.array(zLocation)),
    notes: z.optional(z.array(zNote)),
    quests: z.optional(z.array(zQuest))
});

/**
 * Pinned Entities Data
 * All pinned entities for a game
 */
export const zPinnedEntitiesData = z.object({
    game_id: z.uuid(),
    pinned_entities: zPinnedEntities,
    total_count: z.int()
});

/**
 * Pinned Entities Response
 * Response containing all pinned entities for a game
 */
export const zPinnedEntitiesResponse = z.object({
    data: z.optional(zPinnedEntitiesData)
});

/**
 * Game Create Parameters
 * Parameters for creating a new game
 */
export const zGameCreateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.string(),
    setting: z.optional(z.string())
});

/**
 * Game Create Request
 * Game creation parameters
 */
export const zGameCreateRequest = z.object({
    game: zGameCreateParams
});

/**
 * Notes Response
 * Response containing a list of notes
 */
export const zNotesResponse = z.object({
    data: z.optional(z.array(zNote))
});

/**
 * Linked Character
 * A character with relationship metadata
 */
export const zLinkedCharacterWithPrimary = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    faction_role: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    is_primary: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Faction Links
 * Collections of entities linked to a faction
 */
export const zFactionLinks = z.object({
    characters: z.optional(z.array(zLinkedCharacterWithPrimary)),
    factions: z.optional(z.array(zLinkedFaction)),
    locations: z.optional(z.array(zLinkedLocationWithCurrent)),
    notes: z.optional(z.array(zLinkedNote)),
    quests: z.optional(z.array(zLinkedQuest))
});

/**
 * Faction Links Data
 * Links associated with a faction
 */
export const zFactionLinksData = z.object({
    faction_id: z.uuid(),
    faction_name: z.string(),
    links: z.optional(zFactionLinks)
});

/**
 * Faction Links Response
 * Response containing faction links
 */
export const zFactionLinksResponse = z.object({
    data: z.optional(zFactionLinksData)
});

/**
 * Quest Create Parameters
 * Parameters for creating a new quest
 */
export const zQuestCreateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.string(),
    parent_id: z.optional(z.uuid()),
    status: z.optional(z.enum([
        'preparing',
        'ready',
        'active',
        'paused',
        'completed',
        'cancelled'
    ])),
    tags: z.optional(z.array(z.string()))
});

/**
 * Quest Create Request
 * Quest creation parameters
 */
export const zQuestCreateRequest = z.object({
    quest: zQuestCreateParams
});

/**
 * Objectives Response
 * Response containing a list of objectives
 */
export const zObjectivesResponse = z.object({
    data: z.optional(z.array(zObjective))
});

/**
 * Email Change Request
 * Request to change user email address
 */
export const zEmailChangeRequest = z.object({
    new_email: z.email(),
    password: z.string()
});

/**
 * Objective Create Parameters
 * Parameters for creating a new objective
 */
export const zObjectiveCreateParams = z.object({
    body: z.string(),
    complete: z.optional(z.boolean()),
    note_link_id: z.optional(z.uuid())
});

/**
 * Game Update Request
 * Game update parameters
 */
export const zGameUpdateRequest = z.object({
    game: zGameUpdateParams
});

/**
 * Objective Create Request
 * Request body for creating an objective
 */
export const zObjectiveCreateRequest = z.object({
    objective: zObjectiveCreateParams
});

/**
 * Quest Tree Response
 * Response containing hierarchical quest tree
 */
export const zQuestTreeResponse = z.object({
    data: z.optional(z.array(zQuestTreeNode))
});

/**
 * Location Update Parameters
 * Parameters for updating an existing location (partial updates supported)
 */
export const zLocationUpdateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.optional(z.string()),
    parent_id: z.optional(z.uuid()),
    pinned: z.optional(z.boolean()),
    tags: z.optional(z.array(z.string())),
    type: z.optional(z.enum([
        'continent',
        'nation',
        'region',
        'city',
        'settlement',
        'building',
        'complex'
    ]))
});

/**
 * Location Update Request
 * Location update parameters
 */
export const zLocationUpdateRequest = z.object({
    location: zLocationUpdateParams
});

/**
 * Faction Members Data
 * Characters that are members of a faction
 */
export const zFactionMembersData = z.object({
    faction_id: z.uuid(),
    faction_name: z.string(),
    members: z.optional(z.array(zCharacter))
});

/**
 * Linked Faction
 * A faction with relationship metadata
 */
export const zLinkedFactionWithCurrentLocation = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    description_meta: z.optional(z.string()),
    id: z.uuid(),
    is_active: z.optional(z.boolean()),
    is_current_location: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    name: z.string(),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int()),
    tags: z.optional(z.array(z.string()))
});

/**
 * Location Links
 * Collections of entities linked to a location
 */
export const zLocationLinks = z.object({
    characters: z.optional(z.array(zLinkedCharacterWithCurrentLocation)),
    factions: z.optional(z.array(zLinkedFactionWithCurrentLocation)),
    locations: z.optional(z.array(zLinkedLocation)),
    notes: z.optional(z.array(zLinkedNote)),
    quests: z.optional(z.array(zLinkedQuest))
});

/**
 * Locations Response
 * Response containing a list of locations
 */
export const zLocationsResponse = z.object({
    data: z.optional(z.array(zLocation))
});

/**
 * Quests Response
 * Response containing a list of quests
 */
export const zQuestsResponse = z.object({
    data: z.optional(z.array(zQuest))
});

/**
 * Image Create Parameters
 * Parameters for uploading a new image - multipart/form-data fields
 */
export const zImageCreateParams = z.object({
    alt_text: z.optional(z.string()),
    file: z.string(),
    is_primary: z.optional(z.boolean()),
    position_y: z.optional(z.int().gte(0).lte(100)).default(50)
});

/**
 * Image Create Request
 * Form data for uploading an image - corresponds to image[field] format
 */
export const zImageCreateRequest = z.object({
    image: zImageCreateParams
});

/**
 * Member
 * A game member
 */
export const zMember = z.object({
    email: z.string(),
    joined_at: z.optional(z.string()),
    role: z.string(),
    user_id: z.uuid()
});

/**
 * Location Links Data
 * Links associated with a location
 */
export const zLocationLinksData = z.object({
    links: z.optional(zLocationLinks),
    location_id: z.uuid(),
    location_name: z.string()
});

/**
 * Set Primary Faction Request
 * Parameters for setting a character's primary faction
 */
export const zSetPrimaryFactionRequest = z.object({
    faction_id: z.uuid(),
    role: z.string()
});

/**
 * Character Links Response
 * Response containing character links
 */
export const zCharacterLinksResponse = z.object({
    data: z.optional(zCharacterLinksData)
});

/**
 * Character Response
 * Response containing a single character
 */
export const zCharacterResponse = z.object({
    data: z.optional(zCharacter)
});

/**
 * Characters Response
 * Response containing a list of characters
 */
export const zCharactersResponse = z.object({
    data: z.optional(z.array(zCharacter))
});

/**
 * Image Statistics
 * Statistics about images for an entity
 */
export const zImageStats = z.object({
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest'
    ]),
    has_primary: z.boolean(),
    total_count: z.int().gte(0),
    total_size: z.int().gte(0),
    total_size_mb: z.number()
});

/**
 * Entities Data
 * Game entities data structure
 */
export const zEntitiesData = z.object({
    entities: z.optional(zEntities),
    game_id: z.uuid(),
    game_name: z.string()
});

/**
 * Image Update Parameters
 * Parameters for updating image metadata
 */
export const zImageUpdateParams = z.object({
    alt_text: z.optional(z.string()),
    is_primary: z.optional(z.boolean()),
    position_y: z.optional(z.int().gte(0).lte(100))
});

/**
 * Image Update Request
 * Request body for updating image metadata
 */
export const zImageUpdateRequest = z.object({
    image: z.optional(zImageUpdateParams)
});

/**
 * Objective Update Parameters
 * Parameters for updating an objective
 */
export const zObjectiveUpdateParams = z.object({
    body: z.optional(z.string()),
    complete: z.optional(z.boolean()),
    note_link_id: z.optional(z.uuid())
});

/**
 * Objective Update Request
 * Request body for updating an objective
 */
export const zObjectiveUpdateRequest = z.object({
    objective: zObjectiveUpdateParams
});

/**
 * Faction Create Parameters
 * Parameters for creating a new faction
 */
export const zFactionCreateParams = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    name: z.string(),
    tags: z.optional(z.array(z.string()))
});

/**
 * Faction Create Request
 * Faction creation parameters
 */
export const zFactionCreateRequest = z.object({
    faction: zFactionCreateParams
});

/**
 * Location Creation Link
 * Link definition for location creation
 */
export const zLocationCreationLink = z.object({
    description: z.optional(z.string()),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    is_active: z.optional(z.boolean()).default(true),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

/**
 * Images List Response
 * Response containing a list of images with metadata
 */
export const zImagesListResponse = z.object({
    data: z.array(zImage),
    meta: z.record(z.string(), z.unknown())
});

/**
 * Faction Members Response
 * Response containing faction members
 */
export const zFactionMembersResponse = z.object({
    data: z.optional(zFactionMembersData)
});

/**
 * Entities Response
 * Response containing all game entities
 */
export const zEntitiesResponse = z.object({
    data: z.optional(zEntitiesData)
});

/**
 * Image Statistics Response
 * Response containing image statistics for an entity
 */
export const zImageStatsResponse = z.object({
    data: z.optional(zImageStats)
});

/**
 * Quest Response
 * Response containing a single quest
 */
export const zQuestResponse = z.object({
    data: z.optional(zQuest)
});

/**
 * Signup Request
 * User registration credentials
 */
export const zSignupRequest = z.object({
    email: z.string(),
    password: z.string()
});

/**
 * Location Links Response
 * Response containing location links
 */
export const zLocationLinksResponse = z.object({
    data: z.optional(zLocationLinksData)
});

/**
 * Game
 * A game instance
 */
export const zGame = z.object({
    content: z.optional(z.string()),
    content_plain_text: z.optional(z.string()),
    created_at: z.optional(z.string()),
    id: z.uuid(),
    name: z.string(),
    owner_id: z.uuid(),
    setting: z.optional(z.string()),
    updated_at: z.optional(z.string())
});

/**
 * Game Response
 * Response containing a single game
 */
export const zGameResponse = z.object({
    data: z.optional(zGame)
});

/**
 * Auth Status Response
 * Authentication status response
 */
export const zAuthStatusResponse = z.object({
    authenticated: z.boolean(),
    user: z.optional(zUser)
});

/**
 * Character Update Request
 * Character update parameters
 */
export const zCharacterUpdateRequest = z.object({
    character: zCharacterUpdateParams
});

/**
 * Members Response
 * Response containing a list of game members
 */
export const zMembersResponse = z.object({
    data: z.optional(z.array(zMember))
});

/**
 * Note Creation Link
 * Link definition for note creation
 */
export const zNoteCreationLink = z.object({
    description: z.optional(z.string()),
    entity_id: z.uuid(),
    entity_type: z.enum([
        'character',
        'faction',
        'location',
        'quest',
        'note'
    ]),
    is_active: z.optional(z.boolean()).default(true),
    metadata: z.optional(z.record(z.string(), z.unknown())),
    note_type: z.optional(z.string()),
    relationship_type: z.optional(z.string()),
    strength: z.optional(z.int().gte(1).lte(10))
});

/**
 * Profile Update
 * Parameters for updating user profile
 */
export const zProfileUpdate = z.object({
    username: z.optional(z.string().min(3).max(30))
});

/**
 * Games Response
 * Response containing a list of games
 */
export const zGamesResponse = z.object({
    data: z.optional(z.array(zGame))
});

/**
 * Objective Response
 * Response containing a single objective
 */
export const zObjectiveResponse = z.object({
    data: z.optional(zObjective)
});

/**
 * Faction Response
 * Response containing a single faction
 */
export const zFactionResponse = z.object({
    data: z.optional(zFaction)
});

export const zConfirmEmailChangeData = z.object({
    body: zEmailChangeConfirm,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zConfirmEmailChangeResponse = zSuccessResponse;

export const zGetFactionLinksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        faction_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetFactionLinksResponse = zFactionLinksResponse;

export const zCreateFactionLinkData = z.object({
    body: zLinkRequest,
    path: z.object({
        game_id: z.uuid(),
        faction_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zListLocationsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListLocationsResponse = zLocationsResponse;

export const zCreateLocationData = z.object({
    body: zLocationCreateRequest,
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateLocationResponse = zLocationResponse;

export const zRequestEmailChangeData = z.object({
    body: zEmailChangeRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zRequestEmailChangeResponse = zSuccessResponse;

export const zLogoutUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zLoginUserData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zLoginUserResponse = zLoginResponse;

export const zDeleteLocationLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        location_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zUpdateLocationLinkData = z.object({
    body: zLinkUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        location_id: z.uuid(),
        entity_type: z.enum([
            'note',
            'character',
            'faction',
            'quest',
            'location'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateLocationLinkResponse = z.object({
    entity_id: z.optional(z.uuid()),
    entity_type: z.optional(z.string()),
    location_id: z.optional(z.uuid()),
    message: z.optional(z.string()),
    updated_at: z.optional(z.iso.datetime())
});

export const zListGameMembersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListGameMembersResponse = zMembersResponse;

export const zAddGameMemberData = z.object({
    body: z.object({
        user_id: z.uuid(),
        role: z.optional(z.string())
    }),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetEntityImageStatsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetEntityImageStatsResponse = zImageStatsResponse;

export const zDeleteUserAvatarData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zDeleteUserAvatarResponse = zUser;

export const zUploadUserAvatarData = z.object({
    body: z.object({
        avatar: z.string()
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zUploadUserAvatarResponse = zUser;

export const zDeleteLocationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetLocationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetLocationResponse = zLocationResponse;

export const zUpdateLocationData = z.object({
    body: zLocationUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateLocationResponse = zLocationResponse;

export const zListFactionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListFactionsResponse = zFactionsResponse;

export const zCreateFactionData = z.object({
    body: zFactionCreateRequest,
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateFactionResponse = zFactionResponse;

export const zDeleteCharacterLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid(),
        entity_type: z.enum([
            'note',
            'faction',
            'location',
            'quest',
            'character'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zUpdateCharacterLinkData = z.object({
    body: zLinkUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid(),
        entity_type: z.enum([
            'note',
            'faction',
            'location',
            'quest',
            'character'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateCharacterLinkResponse = z.object({
    character_id: z.optional(z.uuid()),
    entity_id: z.optional(z.uuid()),
    entity_type: z.optional(z.string()),
    message: z.optional(z.string()),
    updated_at: z.optional(z.iso.datetime())
});

export const zListGameEntitiesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListGameEntitiesResponse = zEntitiesResponse;

export const zGetNoteLinksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        note_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetNoteLinksResponse = zNoteLinksResponse;

export const zCreateNoteLinkData = z.object({
    body: zLinkRequest,
    path: z.object({
        game_id: z.uuid(),
        note_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateNoteLinkResponse = z.object({
    entity_id: z.optional(z.uuid()),
    entity_type: z.optional(z.string()),
    message: z.optional(z.string()),
    note_id: z.optional(z.uuid())
});

export const zDeleteObjectiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetObjectiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetObjectiveResponse = zObjectiveResponse;

export const zUpdateObjectiveData = z.object({
    body: zObjectiveUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateObjectiveResponse = zObjectiveResponse;

export const zServeEntityImageFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zSetEntityImageAsPrimaryData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zSetEntityImageAsPrimaryResponse = zImageResponse;

export const zGetLocationTreeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.object({
        start_id: z.optional(z.uuid())
    }))
});

/**
 * Success
 */
export const zGetLocationTreeResponse = zLocationTreeResponse;

export const zRemoveCharacterPrimaryFactionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zRemoveCharacterPrimaryFactionResponse = zCharacterResponse;

export const zGetCharacterPrimaryFactionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetCharacterPrimaryFactionResponse = zCharacterPrimaryFactionResponse;

export const zSetCharacterPrimaryFactionData = z.object({
    body: zSetPrimaryFactionRequest,
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zSetCharacterPrimaryFactionResponse = zCharacterResponse;

export const zPinCharacterData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPinCharacterResponse = zCharacterResponse;

export const zGetFactionMembersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        faction_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetFactionMembersResponse = zFactionMembersResponse;

export const zListQuestsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListQuestsResponse = zQuestsResponse;

export const zCreateQuestData = z.object({
    body: zQuestCreateRequest,
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateQuestResponse = zQuestResponse;

export const zListGameImagesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.object({
        primary_first: z.optional(z.boolean()),
        limit: z.optional(z.int()),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Success
 */
export const zListGameImagesResponse = zImagesListResponse;

export const zDeleteNoteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetNoteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetNoteResponse = zNoteResponse;

export const zUpdateNoteData = z.object({
    body: zNoteUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateNoteResponse = zNoteResponse;

export const zGetCharacterLinksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetCharacterLinksResponse = zCharacterLinksResponse;

export const zCreateCharacterLinkData = z.object({
    body: zLinkRequest,
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zListCharactersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListCharactersResponse = zCharactersResponse;

export const zCreateCharacterData = z.object({
    body: zCharacterCreateRequest,
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateCharacterResponse = zCharacterResponse;

export const zDeleteGameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetGameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetGameResponse = zGameResponse;

export const zUpdateGameData = z.object({
    body: zGameUpdateRequest,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateGameResponse = zGameResponse;

export const zGetEntityPrimaryImageData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetEntityPrimaryImageResponse = zImageResponse;

export const zGetGameEntityTreeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.object({
        depth: z.optional(z.int()),
        start_entity_type: z.optional(z.string()),
        start_entity_id: z.optional(z.uuid())
    }))
});

/**
 * Success
 */
export const zGetGameEntityTreeResponse = zEntityTreeResponse;

export const zUnpinCharacterData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        character_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUnpinCharacterResponse = zCharacterResponse;

export const zSignupUserData = z.object({
    body: zSignupRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zSignupUserResponse = zLoginResponse;

export const zGetAuthStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetAuthStatusResponse = zAuthStatusResponse;

export const zDeleteQuestData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetQuestData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetQuestResponse = zQuestResponse;

export const zUpdateQuestData = z.object({
    body: zQuestUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateQuestResponse = zQuestResponse;

export const zGetLocationLinksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        location_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetLocationLinksResponse = zLocationLinksResponse;

export const zCreateLocationLinkData = z.object({
    body: zLinkRequest,
    path: z.object({
        game_id: z.uuid(),
        location_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetUserProfileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetUserProfileResponse = zUser;

export const zUpdateUserProfileData = z.object({
    body: zProfileUpdate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateUserProfileResponse = zUser;

export const zListGameObjectivesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListGameObjectivesResponse = zObjectivesResponse;

export const zDeleteEntityImageData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetEntityImageData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetEntityImageResponse = zImageResponse;

export const zUpdateEntityImageData = z.object({
    body: zImageUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateEntityImageResponse = zImageResponse;

export const zDeleteNoteLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        note_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zUpdateNoteLinkData = z.object({
    body: zLinkUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        note_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateNoteLinkResponse = z.object({
    entity_id: z.optional(z.uuid()),
    entity_type: z.optional(z.string()),
    message: z.optional(z.string()),
    note_id: z.optional(z.uuid()),
    updated_at: z.optional(z.iso.datetime())
});

export const zListObjectivesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListObjectivesResponse = zObjectivesResponse;

export const zCreateObjectiveData = z.object({
    body: zObjectiveCreateRequest,
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateObjectiveResponse = zObjectiveResponse;

export const zDeleteCharacterData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetCharacterData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetCharacterResponse = zCharacterResponse;

export const zUpdateCharacterData = z.object({
    body: zCharacterUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateCharacterResponse = zCharacterResponse;

export const zGetQuestLinksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetQuestLinksResponse = zQuestLinksResponse;

export const zCreateQuestLinkData = z.object({
    body: zLinkRequest,
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zDeleteFactionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetFactionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetFactionResponse = zFactionResponse;

export const zUpdateFactionData = z.object({
    body: zFactionUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateFactionResponse = zFactionResponse;

export const zListEntityImagesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.object({
        primary_first: z.optional(z.boolean())
    }))
});

/**
 * Success
 */
export const zListEntityImagesResponse = zImagesListResponse;

export const zUploadEntityImageData = z.object({
    body: z.object({
        'image[file]': z.string(),
        'image[alt_text]': z.optional(z.string()),
        'image[is_primary]': z.optional(z.boolean()),
        'image[position_y]': z.optional(z.int())
    }),
    path: z.object({
        game_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'quest',
            'note'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zUploadEntityImageResponse = zImageResponse;

export const zCompleteObjectiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        objective_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zCompleteObjectiveResponse = zObjectiveResponse;

export const zRemoveGameMemberData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zUncompleteObjectiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        objective_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUncompleteObjectiveResponse = zObjectiveResponse;

export const zDeleteFactionLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        faction_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'location',
            'quest',
            'note',
            'faction'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zUpdateFactionLinkData = z.object({
    body: zLinkUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        faction_id: z.uuid(),
        entity_type: z.enum([
            'note',
            'character',
            'location',
            'quest',
            'faction'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateFactionLinkResponse = z.object({
    entity_id: z.optional(z.uuid()),
    entity_type: z.optional(z.string()),
    faction_id: z.optional(z.uuid()),
    message: z.optional(z.string()),
    updated_at: z.optional(z.iso.datetime())
});

export const zListNotesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListNotesResponse = zNotesResponse;

export const zCreateNoteData = z.object({
    body: zNoteCreateRequest,
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateNoteResponse = zNoteResponse;

export const zListPinnedEntitiesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListPinnedEntitiesResponse = zPinnedEntitiesResponse;

export const zListGamesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListGamesResponse = zGamesResponse;

export const zCreateGameData = z.object({
    body: zGameCreateRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateGameResponse = zGameResponse;

export const zDeleteQuestLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        entity_type: z.enum([
            'character',
            'faction',
            'location',
            'note',
            'quest'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zUpdateQuestLinkData = z.object({
    body: zLinkUpdateRequest,
    path: z.object({
        game_id: z.uuid(),
        quest_id: z.uuid(),
        entity_type: z.enum([
            'note',
            'character',
            'faction',
            'location',
            'quest'
        ]),
        entity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateQuestLinkResponse = z.object({
    entity_id: z.optional(z.uuid()),
    entity_type: z.optional(z.string()),
    message: z.optional(z.string()),
    quest_id: z.optional(z.uuid()),
    updated_at: z.optional(z.iso.datetime())
});

export const zGetQuestTreeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        game_id: z.uuid()
    }),
    query: z.optional(z.object({
        start_id: z.optional(z.uuid())
    }))
});

/**
 * Success
 */
export const zGetQuestTreeResponse = zQuestTreeResponse;